version: '3'

services:
  web_service:
    build:
      context: ./albbacompany_web
      dockerfile: Dockerfile
    container_name: albbacompany_web
    privileged: true
    networks:
      - albbacompany_network
    ports:
      - "8080:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  file_server:
    build:
      context: ./albbacompany_file
      dockerfile: Dockerfile
    container_name: albbacompany_file
    privileged: true
    networks:
      - albbacompany_network
    ports:
      - "8081:80"

networks:
  albbacompany_network:
    external: true
